### ISSUE TITLE
feat: sync from proven root

### ISSUE THREAD

**Issue by drspacemn** [eigerco/beerus#550]
Once we are up-to-date with the [l1 state root](https://github.com/keep-starknet-strange/beerus/blob/a4e8c2be92d8bdaa36a4e90e760323f431405754/crates/core/src/client.rs#L126), we can pull the next block from the untrustred RPC and compute the next root based on the re-exution of the block:
- fetch and format the [block body](https://github.com/starkware-libs/starknet-api/blob/1dea9d95f847a8b87667bcaf55456742ca203db3/src/block.rs#L39)
- fetch and format [block header](https://github.com/starkware-libs/starknet-api/blob/1dea9d95f847a8b87667bcaf55456742ca203db3/src/block.rs#L22)
- [hash the block](https://docs.starknet.io/documentation/architecture_and_concepts/Network_Architecture/header) 

This will give a less safe guarantee that this data is accurate i.e. this RPC could only have lied in the blocks that L2 is behind L1. This is not ideal but will be the tradeoffs of using a light client.

When we re-execute these blocks we will also store/cache the new state root, block, number and block hash ideally via a cache solution similar to papyrus uses like [tempfile](https://docs.rs/tempfile/latest/tempfile)

We can then respond to requests that are past the last proven l1 block with some degree of confidence, we'll need to figure out how we can communicate this to the user.

**Comment by umarcrew** [comment]
Good project

**Comment by pierre-l** [comment]
Putting this here for the record: Pathfinder's `getEvent` implementation in v0.10.4 may return an array with a single zeroed key when the sequencer shows an empty array instead.
This breaks block hashing.
I'm currently preparing to test against Pathfinder 0.11.0-rc0.

**Comment by pierre-l** [comment]
Discussed again yesterday, this is unlikely to bring sufficient guarantees, while it also brings non-trivial challenges:
- we'd have to carefully orchestrate the synchronization in the case Beerus is lagging behing the L1 updates or in the case of a soft fork
- block hashing is more computational intensive than expected, taking roughly 500-1000ms per block.

Adapting the Starknet protocol for light clients is the way to go.
