### ISSUE TITLE
chore: mainnet integration test failures

### ISSUE THREAD

**Issue by pierre-l** [eigerco/beerus#568]
Investigate why the integration tests are currently failing.
Fix them.

- [ ] starknet_call
- [ ] starknet_estimateFee
- [ ] starknet_estimateFeeSingle
- [ ] starknet_getBalance
- [ ] starknet_getBlockWithTxHashes
- [ ] starknet_getBlockWithTxs
- [ ] starknet_getClass
- [ ] starknet_getClassAt
- [ ] starknet_getClassHashAt
- [ ] starknet_getNonce
- [ ] starknet_getProof
- [ ] starknet_getStorageAt
- [ ] starknet_getTransactionReceipt

**Comment by pierre-l** [comment]
@tonypony220 What do you mean by Starknet RPC?

**Comment by tonypony220** [comment]
@pierre-l https://github.com/starkware-libs/starknet-specs/tree/v0.6.0
