### ISSUE TITLE
feat: RPC codegen based on OpenRPC spec

### ISSUE THREAD

**Issue by sergey-melnychuk** [eigerco/beerus#573]
To consider: https://github.com/sergey-melnychuk/iamgroot

**Comment by pierre-l** [comment]
RPC codegen based on OpenRPC spec, isn't that what [`starknet-rs`](https://github.com/xJonathanLEI/starknet-rs) already does? It's far from being perfect but it has worked so far.
I'm not sure how good it is besides data structures though, regarding OpenRPC validation logic & al. How far should this generation go?

**Comment by pierre-l** [comment]
`starknet-rs` generates [this](https://github.com/xJonathanLEI/starknet-rs/blob/master/starknet-core/src/types/codegen.rs). Pure DTOs, little validation besides - I expect - hex format and such.
