### ISSUE TITLE
feat: `starknet_getTransactionStatus` support

### ISSUE THREAD

**Issue by pierre-l** [eigerco/beerus#585]
`getTransactionStatus` isn't currently supported.

See https://github.com/eigerco/beerus/blob/1c10839fa6ee3ab740fbf026d94001d6f6ce1977/crates/rpc/src/api.rs#L67

**Comment by psychiller** [comment]
I would like to work on this, would appreciate some pointers.

**Comment by pierre-l** [comment]
Hello @psychiller!

[This one](https://github.com/eigerco/beerus/issues/586#issue-2105170373) probably is a better first issue. I left some pointers in the issue description. Let me know if you need more.

**Comment by psychiller** [comment]
Thank you for heads up, can you assign that one.
