### ISSUE TITLE
feat: `starknet_specVersion` support

### ISSUE THREAD

**Issue by pierre-l** [eigerco/beerus#586]
This method is missing from Beerus.

Implementing it should be fairly straightforward.
The method should be added to the [`api` module](https://github.com/eigerco/beerus/blob/main/crates/rpc/src/api.rs#L33).
Once done, the [corresponding test](https://github.com/eigerco/beerus/blob/main/etc/rpc/mainnet/starknet_specVersion.hurl-disabled) should be restored.

The spec version currently used in Beerus is [`0.5.1`](https://github.com/starkware-libs/starknet-specs/tree/v0.5.1)

**Comment by psychiller** [comment]
I will take this one.

**Comment by pierre-l** [comment]
Fixed in #593 
Thanks @psychiller!
