### ISSUE TITLE
feat: RPC spec version check on startup

### ISSUE THREAD

**Issue by pierre-l** [eigerco/beerus#596]
Beerus should call `starknet_specVersion` on startup to make sure the backend Starknet node specified via the config uses the same spec.

A constant should be extracted from [this value](https://github.com/eigerco/beerus/blob/main/crates/rpc/src/api.rs#L528).

We should check if the Starknet OpenRPC spec effectively uses semver. If it's the case, we _might_ want to just enforce the same major version, or major+minor.

In the case of a mismatch, an error/fatal log should be printed and Beerus should exit.

**Comment by psychiller** [comment]
I can take it up.
I will move spec_version value to config file from we read RPC endpoints. And then during `Client::new` function, a call can be made to starknet node and then check the result. If there is any better way, I could do it that way as well.

**Comment by pierre-l** [comment]
> config file
I'd rather have this as a code constant since this version is dictated by the `starknet-rs` version in use in Beerus.

**Comment by psychiller** [comment]
I was trying to check by implementing it and found we need to upgrade `starknet-rs` to new version. In `0.6.0` `spec_version` function is not available in provider.

**Comment by pierre-l** [comment]
Ah, bummer.
The problem with more recent versions of `starknet-rs` is that they are based on [starknet-specs:v6.0.0](https://github.com/starkware-libs/starknet-specs/tree/v0.6.0), which AFAIK isn't supported by major API providers like Alchemy yet.
I expect support for the 0.6.0 spec will come anytime soon as 0.7 is already around the corner, but in the meantime our immediate position is to stay on 0.5.1 on the main branch.

**Comment by pierre-l** [comment]
We could test more API providers from the [official list](https://docs.starknet.io/documentation/tools/api-services/), check which ones support 0.6.0 and if we have a few of these, migrate to 0.6.0 and list these providers in the README.md.

How does that sound @sergey-melnychuk?

**Comment by psychiller** [comment]
Yeah, this should be straightforward now.
