### ISSUE TITLE
test: Add more integration test scenarios

### ISSUE THREAD

**Issue by pierre-l** [eigerco/beerus#625]
Add more test scenarios to the [chain-agnostic integration tests](https://github.com/eigerco/beerus/blob/main/crates/rpc/tests/rpc.rs) cover the following methods:

- [ ] `starknet_call`
- [ ] `starknet_estimateFee`
- [ ] `starknet_estimateFeeSingle`
- [ ] `starknet_getEvents`
- [ ] `starknet_getStateUpdate`
- [ ] `starknet_getStorageAt`
- [ ] `starknet_getTransactionReceipt`
- [ ] `starknet_syncing`
- [ ] `pathfinder_getProof`

   Extended endpoints (unsupported by starknet-rs' `JsonRpcClient`):

- [ ] `starknet_getStateRoot`
- [ ] `starknet_getProof`
- [ ] `starknet_getBalance`

**Comment by sergey-melnychuk** [comment]
https://github.com/eigerco/beerus/pull/627
