### ISSUE TITLE
feat(ci): report code coverage

### ISSUE THREAD

**Issue by sergey-melnychuk** [eigerco/beerus#684]
https://github.com/taiki-e/cargo-llvm-cov
https://github.com/mozilla/grcov

**Comment by jrmncos** [comment]
hey team! I would like to tackle this one

**Comment by sergey-melnychuk** [comment]
Current state: 

`cargo tarpaulin --exclude-files src/gen.rs --exclude-files src/bin/* --exclude-files web/* --out html`

<img width="559" alt="Screenshot 2024-09-28 at 21 00 24" src="https://github.com/user-attachments/assets/14a4ca87-96a8-4c4b-9e10-58b06ab26091">

Unfortunately running coverage job with `tarpaulin` turns out to be too much for a Github Actions worker, so right now I am looking for a workaround.

**Comment by sergey-melnychuk** [comment]
https://github.com/eigerco/beerus/pull/787#issuecomment-2431369794
