### ISSUE TITLE
test: create and deploy new account

### ISSUE THREAD

**Issue by ICavlek** [eigerco/beerus#694]
Following workflow should be investigated:

1. Creating account smart contract
2. Creating account in wallet
3. Declaring account
4. Deploying account

Used assets

- Standard account - https://book.starknet.io/ch04-03-standard-account.html
- katana 0.6.0-alpha.7 - node for local development

Account declare
- [x] https://github.com/eigerco/beerus/issues/717
- [x] https://github.com/eigerco/beerus/issues/730
- [x] https://github.com/eigerco/beerus/issues/731
- [x] https://github.com/eigerco/beerus/issues/732

Account deploy
- [x] https://github.com/eigerco/beerus/issues/718
- [x] https://github.com/eigerco/beerus/issues/761

Account declare deploy on testnet
- [x] https://github.com/eigerco/beerus/issues/777

**Comment by jrmncos** [comment]
hey @ICavlek I would like to onboarding on this project and to tackle this issue

**Comment by ICavlek** [comment]
> hey [@ICavlek](https://github.com/ICavlek) I would like to onboarding on this project and to tackle this issue

Hi @jrmncos, you can apply for the open positions at the company's website:
https://www.eiger.co/company#positions

**Comment by jrmncos** [comment]
thanks @ICavlek I'll do it, but, can I take the issue in the meanwhile?

**Comment by ICavlek** [comment]
> thanks [@ICavlek](https://github.com/ICavlek) I'll do it, but, can I take the issue in the meanwhile?

Issue assignments are only for employees by Eiger and I am currently working on this one. If you want to introduce specific changes, create a PR and we will review it.

**Comment by jrmncos** [comment]
oh, got it, I though that I could ask for any issue, just to confirm, with this one is the same right? https://github.com/eigerco/beerus/issues/684 or can I create a PR with the changes?

In any case, I will apply :)

**Comment by ICavlek** [comment]
> oh, got it, I though that I could ask for any issue, just to confirm, with this one is the same right? [#684](https://github.com/eigerco/beerus/issues/684) or can I create a PR with the changes?
> 
> In any case, I will apply :)

It's the same, you won't be assigned to any issue, but you can work on it and create a PR for it
