### ISSUE TITLE
test: submitting transactions (INVOKE)

### ISSUE THREAD

**Issue by ICavlek** [eigerco/beerus#697]
Following workflow should be investigated:
1. Creating account smart contract
2. Declaring & Deploying an account
3. Declaring & Deploying smart contract
4. Interacting with a smart contract using deployed account

[INVOKE transaction](https://docs.starknet.io/architecture-and-concepts/network-architecture/transactions/#invoke_transaction)

This test case will re-use code from the other test cases, like:
https://github.com/eigerco/beerus/issues/694
https://github.com/eigerco/beerus/issues/695

**Comment by sergey-melnychuk** [comment]
Closed by https://github.com/eigerco/beerus/issues/694
