### ISSUE TITLE
test: test_getStorageAt with BlockTag Latest

### ISSUE THREAD

**Issue by ICavlek** [eigerco/beerus#711]
Current integration test for starknet_getStorageAt contains requests by Number, Hash and BlockTag Pending. BlockTag Latest is not implemented because context setup would need to be updated based on the latest block which is currently produced every ~20 secs.

https://github.com/eigerco/beerus/blob/b59496d624f5c9e52876c8ffcc1a0854e0cff313/tests/rpc.rs#L244

In scope of this issue, an integration test with BlockTag Latest needs to be created. Challenge is the live network which is constantly providing new blocks.

**Comment by oluwa-peski** [comment]
Hello @ICavlek Is this still open for contributions?

**Comment by ICavlek** [comment]
> Hello @ICavlek Is this still open for contributions?

Hi, it is still open for contributions

**Comment by sergey-melnychuk** [comment]
`test_getStorageAt` from `tests/rpc.rs` uses plain client that does not verify proofs for the returned value, so there is no need to update test context with latest block as it will not have any effect on the test.
