### ISSUE TITLE
feat: scarb support with valid account contracts

### ISSUE THREAD

**Issue by ICavlek** [eigerco/beerus#803]
Scarb is a tool from starknet environment that is used to compile smart contracts written in cairo. In scope of this issue, it has to be investigated and solved use case of scarb within the beerus test environment: as environment tool via .sh script, docker image or integrated library. 
Additionally, valid account contract is going to be provided that can be reused, modified with tools from environment and declared/deployed to starknet repeatedly. Suggested difference between the contracts is id member in the struct, which can be incremented before new declare/deploy test run.

**Comment by MPSxDev** [comment]
I would like to take on this issue and I am ready to work on it immediately. I look forward to being assigned.

**Comment by ICavlek** [comment]
> I would like to take on this issue and I am ready to work on it immediately. I look forward to being assigned.

Pull request is already open and the issue is nearly done.
